name: 'Setup environment'
description: 'Checkout, start minikube, and install Go'
runs:
  using: composite
  steps:
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'
