apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cm
  labels:
    app: test-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cm
  template:
    metadata:
      labels:
        app: test-cm
    spec:
      containers:
      - name: test-cm
        image: htcondor/cm
        env:
        - name: _CONDOR_TRUST_DOMAIN
          value: test-cm
        - name: _CONDOR_ALLOW_WRITE
          value: '*'
        volumeMounts:
        - name: pool-passwd
          mountPath: /etc/condor/passwords-orig.d/
      volumes:
      - name: pool-passwd
        configMap:
          name: pool-passwd
---
apiVersion: v1
kind: Service
metadata:
  name: test-cm
spec:
  selector:
    app: test-cm
  ports:
    - protocol: TCP
      port: 9618
      targetPort: 9618
