name: Run K8s Integration Tests
on:
  workflow_dispatch: 
jobs:
  test-ospool-ep:
    strategy:
      matrix:
        cvmfs_type: ['CvmfsExec', 'CvmfsBindMount']
    runs-on: ubuntu-22.04
    name: Run OSPool EP test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup environment
      uses: ./.github/actions/setup
    - name: 'Test OSPool EP with ${{ matrix.cvmfs_type }}'
      run: go test ./test -v -run TestOSPoolEP${{ matrix.cvmfs_type }} -timeout 15m
    - name: 'Upload Test Logs'
      uses: actions/upload-artifact@v4
      with:
        name: ospool-ep-${{ matrix.cvmfs_type }}
        path: /tmp/k8s-tests
        retention-days: 5
  
  test-pelican:
    strategy:
      matrix:
        version: ['v7.22.0', 'v7.24.2']
    runs-on: ubuntu-22.04
    name: Run Pelican tests
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup environment
      uses: ./.github/actions/setup
    - name: Install Pelican CLI
      run: |
          wget https://dl.pelicanplatform.org/7.24.2/pelican_7.24.2-1_amd64.deb
          sudo dpkg -i pelican_7.24.2-1_amd64.deb
    - name: 'Test Pelican version ${{ matrix.version }}'
      env:
        PELICAN_Tag: ${{ matrix.version }}
      run: go test ./test -v -run TestPelican -timeout 15m
    - name: 'Upload Test Logs'
      uses: actions/upload-artifact@v4
      with:
        name: pelican-${{ matrix.version }}
        path: /tmp/k8s-tests
        retention-days: 5
