name: Run K8s Integration Tests
on:
  workflow_dispatch: 
jobs:
  test-ospool-ep-cvmfsexec:
    runs-on: ubuntu-22.04
    name: Run OSPool EP test (cvmfsexec)
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'
    - name: 'Test OSPool EP with cvmfsexec'
      run: go test ./test -v -run TestOSPoolEPCvmfsexec
      
  test-ospool-ep-bind-mount:
    runs-on: ubuntu-22.04
    name: Run OSPool EP tests (cvmfs bind mount)
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'
    - name: Setup CVMFS
      run: sudo scripts/setup_cvmfs.sh
    - name: Bind-Mount CVMFS into Minikube
      run: minikube mount /cvmfs:/cvmfs &
    - name: 'Test OSPool EP with cvmfs bind mount'
      run: go test ./test -v -run TestOSPoolEPCvmfsBindMount
