apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvmfs-singularity
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: /var/lib/cvmfs-k8s/singularity.opensciencegrid.org
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-singularity
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2G
  storageClassName: ""
  volumeName: cvmfs-singularity
